apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:r/mquTaWMn4mEx79tpoiOfJgqPi5IWMQU4A=,iv:efhdmGmtKH+kMGUnxamXBgcnSUJqN2dYhKlKuDjaAO8=,tag:X28jhd8DBZedgM/Y/hnfJQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:/+1W8mdRKBttlucleYnxpfXAQjr6dRocDsYE6OlEgkdEcza0Mw==,iv:IrZiiByfZoA8X7/G65Sa48u61T3Mcyxu+av+j9Ja1+4=,tag:F4gOwhHv3dSCARuh2p/Ihg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:x34QS15vRPgz9u2yuFWTul0=,iv:9Wb21GyJ2cPXgiNib69KZvXJkmDkjTuyDilU+3RUKgI=,tag:FxcIhQ7effq1BVU0UH1Dxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcG5YM1FsWGFVclJTb0JM
            cW5XYSt0WTlXUjFoMDhtb2FLRmdHNk0wYTFFCmRjU2hMQUgxOVdaSHFBREI1dW43
            WUdGbG1LNFBsR1dnelF3Vm9FdHl5bGcKLS0tIGhueUordFh5Nmp1dXY2NkVGSTV5
            Zy9DMFdlT2VNRHIyWUJLZ0VJU2VOR0EKMlAy71hwhLAtM9uqOf/eDJ44RgZnTkJR
            N6eEv+euU7ASo6vlIgMVSqYRqf9kr+dv8CQIltuU4aPSFxF2GMFFXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T11:48:20Z"
    mac: ENC[AES256_GCM,data:GeYkwqaOOMykNW/SWpfvCa1R+f9GlbgOgasXkjBrRo73mTNo7xQKND22bjUR+TKWnYZdVTkHj0akPIuALTVsS+ykg9PUJKx/GeVIZutcsh80bqWK8qlWG+lAe/WiJeZ5/itI+/erIDy5eQbQIOPcbbMixrenO6XaV6aRRiI9D34=,iv:BCZ8XddbzGp+wYSt/VC0tkmzMeoQN3yv2fRTUWm23RI=,tag:0IhQEZvxHDpl31CUPtu+0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
