---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app minio
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2023-02-27T18-10-45Z
    env:
      TZ: "${TIMEZONE}"
      MINIO_UPDATE: "off"
      MINIO_ROOT_USER:
        valueFrom:
          secretKeyRef:
            name: minio
            key: root-user
      MINIO_ROOT_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: minio
            key: root-password
      # MINIO_PROMETHEUS_AUTH_TYPE: "public"
      # MINIO_PROMETHEUS_URL: http://kube-prometheus-stacks-prometheus.monitoring:9090
      # MINIO_PROMETHEUS_JOB_ID: minio
      MINIO_BROWSER_REDIRECT_URL: https://minio.${SECRET_DOMAIN}
      MINIO_SERVER_URL: https://s3.${SECRET_DOMAIN}
      CONSOLE_MINIO_SERVER: https://minio.${SECRET_DOMAIN}
      MINIO_DOMAIN: "https://s3.${SECRET_DOMAIN}"
      MINIO_API_CORS_ALLOW_ORIGIN: https://minio.${SECRET_DOMAIN},https://s3.${SECRET_DOMAIN}
      # MINIO_IDENTITY_OPENID_CONFIG_URL: "https://auth.${CLUSTER_DOMAIN}/.well-known/openid-configuration"
      # MINIO_IDENTITY_OPENID_CLIENT_ID: minio
      # MINIO_IDENTITY_OPENID_CLIENT_SECRET: "${SECRET_MINIO_OAUTH_CLIENT_SECRET}"
      # MINIO_IDENTITY_OPENID_SCOPES: "openid,profile,email,groups"
      # MINIO_IDENTITY_OPENID_REDIRECT_URI: "https://minio.${CLUSTER_DOMAIN}/oauth_callback"
    envFrom:
      - secretRef:
          name: *app
    args: ["server", "/data", "--console-address", ":9001"]
    service:
      main:
        enabled: true
        ports:
          http:
            port: &port-console 9001
          api:
            enabled: true
            port: &port-api 9000
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: api
            scheme: http
            path: /minio/v2/metrics/cluster
            interval: 1m
            scrapeTimeout: 10s
            bearerTokenSecret:
              name: minio-prometheus
              key: token
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/appName: "Minio Console"
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:pail
        hosts:
          - host: &host-console "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port-console
        tls:
          - hosts:
              - *host-console
            secretName: minio-main-tls
      s3:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.home.arpa/enabled: "true"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-body-size: 5000m
          nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            chunked_transfer_encoding off;
          hajimari.io/enable: "false"
        hosts:
          - host: &host-api "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port-api
        tls:
          - hosts:
              - *host-api
            secretName: minio-s3-tls
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: minio-nfs
        mountPath: /data
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
