---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: 12.1.8
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  targetNamespace: minio
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: minio
    persistence:
      existingClaim: minio
    volumePermissions:
      enabled: true
    ingress:
      enabled: true
      annotations:
        external-dns.home.arpa/enabled: "true"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
        nginx.ingress.kubernetes.io/proxy-body-size: 5000m
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          chunked_transfer_encoding off;
      hostname: "minio.${SECRET_DOMAIN}"
    apiIngress:
      enabled: true
      annotations:
        external-dns.home.arpa/enabled: "true"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
        nginx.ingress.kubernetes.io/proxy-body-size: 5000m
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          chunked_transfer_encoding off;
      hostname: "s3.${SECRET_DOMAIN}"
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/minio/v2/metrics/cluster"
      prometheus.io/port: "9000"
      reloader.stakater.com/auto: "true"
    nodeSelector:
      feature.node.kubernetes.io/custom-usb-backupdrive: "true"
    auth:
      rootUser: "admin"
      rootPassword: "Pax1106Pax"
    metrics:
      serviceMonitor:
        enabled: "${MONITORING_PROMETHEUS}"
