---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-minio
  namespace: storage
spec:
  storageClassName: nfs-minio
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.10.10
    path: "/nfsshare"
  mountOptions:
    - nfsvers=4.2
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-minio
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-minio
  resources:
    requests:
      storage: 1Mi
