kind: ENC[AES256_GCM,data:fUQdoD1B,iv:rT5M9vzVwohY+VePV1DwoXV/OsYYgMUVceIGDW1qVQo=,tag:QEmrhWNKGN+GjewZakp5+Q==,type:str]
ansible_user: ENC[AES256_GCM,data:of+RbDJBAw==,iv:3h2omXrA2h64p+zCogFoSWWmyiR82XcWjRpxdEVTqrs=,tag:E0vlOtA5xwTDJUW+m3CfLg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:HWMOcqgQOlAOPw==,iv:L+gJ3+foBe5vBrxviHwEGalQjIwn4i3km4vNKGZGXCg=,tag:R3WBouXTbWNC4aBEg6U04w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N2w2WE1QaytiVEVndkt3
            YlhEdFNxNW5UcVQ1Y3duTHRUV1BHY2tLWnlRCjZTLzgyUEhWOVhDNytEZERNWkdH
            K3owWEU4b0kyZVp0WnB0Q29MWEZadnMKLS0tIDlBazBNcnMvT2pKMDVmZ1d3bGRX
            WFpUaHZ1czYvRExjYnVZSkdWM1RpR0UKFgvbZrhSm7+wxGQ7QcE/oLXsTBMcSBCi
            +dKmSWrV6pxRe2GD30wrNJuUWJk+vyURzAcahn5Ogg0rpQ8Ih/KhLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-05T17:08:38Z"
    mac: ENC[AES256_GCM,data:G4ECvDydtg/ZFb3PsA7geJJt1i7XNBq2AMRuVpOEcsiRy7/VFC1lU6RmZsxhQoRUBMazkaMB0zmmJTfIp8Tr8M5lX78PNGaxHAHvK2jOsIoogynk2TIwH4Fe3BcqDHBrS3lQkiGFCiEA1swBy6uCUvdQOwzcNsvtvC6foO2FyEQ=,iv:d1Q9uZfviVoxLagnrUzMaEGyRuYR4y1IoDC4Go1g61E=,tag:vhIi8Rx6hsWwL9LgsYG0/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
