kind: ENC[AES256_GCM,data:d7uEcPdQ,iv:tKU6H9TjH9gnmveCrd6uLZB5GkloGvkPR0AaX2zf0jo=,tag:PVPurQrgFnkRB3lJJuhd6Q==,type:str]
ansible_user: ENC[AES256_GCM,data:ht1wjq8RnQ==,iv:IjHhbmrQTzyVbNVQy97c5IbJ2FGlV6MzgMrhLtvNUoU=,tag:QZLuAmKZr1VdAa0vClEYbA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:STwJJ/eEHTgJcQ==,iv:INeGgMXP69JSRkffKKmygof+zDUDXuhqIU2yrXN4SpE=,tag:qnqSfTQ8zYny/I7rcaZ4mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndVBNMVB0MnMxejBoK3hM
            RGtSd2UrMVJQZkNjRXl1Rlo1dnAwc3h3MDNrCkhwaWI4N0RLOStGSk5iUnJES0w5
            WVZoNWVxY2pvcCtPVEwrbWVJU3Q4QTAKLS0tIElXTzFsQWowVFpxQ1NpeW5HSzls
            SFBXeGs4TC9TczdHSUF1bVEvNHAvUjgK3GIQczQu6yHfdVsuvV1oytfbE5a5oiML
            hQS9sive6bdhkmtycMaKw9NAxtR2IvV4O/vtJJCdiX4/i8ENGUBVvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-05T17:08:38Z"
    mac: ENC[AES256_GCM,data:PD0btl/eC27By9+blrju+KxG6qC29U0QVa2e31FcOf6oDpQWaE+V8lWOMTaUTGN3uiDUiivMaZfMpW9l72dxoxeJH1zMZ2w8pAyPKOs4GNQQMrjsf/0x/55oAbopI3DOh0TtZO77od0TV4N39DiY9keR5jqlvhbKE2L2qk4GcrU=,iv:NDOilMlZhi22cNEOIAuGfd3I664Xr2NGyAIZSZKfK4M=,tag:5ex/DpKPljOHa6kmbbq2YQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
