kind: ENC[AES256_GCM,data:gBK8nxpR,iv:8YI+4e4Chdq+INqL4xYJbYraEKgLR4wtmxUSgvgpWTI=,tag:IskndyPYwRggFhzt6Ddntw==,type:str]
ansible_user: ENC[AES256_GCM,data:hBPZNqmk1A==,iv:F8GrVMiafXK3yZFRkYfl7jkAKhJGjxlfiFqyy2Vt4TY=,tag:RHjnJ733NfiQVS7ndtBJaw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:dofvbXb5aewPpw==,iv:Q83l89oHMLTChnhoi8zYnaiBZsse/LLjVtaDPPBIwwA=,tag:LoS8ppl5eBUhF+UG8SWnMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWFBnNWlVU2lRV1grc1RE
            VHBqMUw2RUtHM1J1MVZEZ1JlbU56eXdBS3c0ClNkN2ovVGNNMEIvT0J5MzgxeFFH
            b0x3a3VlV2NRTFplaWFrbVBzOTlNT1UKLS0tIHlVVGlXWEpNRnZHdzRycGpCbkhs
            eHZEelIwbW1PS0o3VkNJTmpaN01ZTDgK9WSbi+tyBk4HyFOyYdEavSqyh9IcANBn
            WVMk1HPhTXI28mGTEabmJnN2OB71RJfzX2JSYYqLw6oVH5V4YdpKxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-05T17:08:38Z"
    mac: ENC[AES256_GCM,data:Pa+ZnWxfsYg13vqoKSFaBfpY9q26jICdN/Gf2VtsEb1Nl97XYPVqBHPR7Pnq/8WxvS3oO/g3KHetcmztcfWqHDFyqyQ6N/UHKVGm+GM3wSgvlDGsGkVq7pvz3uR3HpSaMabythyW28Yx7XSblmwXzOIB12Jm3Rxy/tT8kH/uKO4=,iv:Ni88zgptijOvhAZip/8TAOGE5NP7Oqd0iJCbqTjoSe4=,tag:MCnbY2OKKLFl5m2LNTWU0g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
