kind: ENC[AES256_GCM,data:8JTFADO6,iv:e1WQxBxHleMQr39jlvJkPxVxFy3dZQAfoga2nlHPoUg=,tag:FzJNoZoz55zVAg/iOFMRtg==,type:str]
ansible_user: ENC[AES256_GCM,data:RUi8GgGMSA==,iv:zIQKqnlkw8GgzlgFJbBWzlJHeX3z3BNcG4N+q7K9PSA=,tag:eIMtuuedcCTJE/SVEDsR0g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:+Vn2hiWEVke65A==,iv:8TEw5gef+q14GPL/LCAqB+BGyw9pW/hFWlOO7QQmjj8=,tag:enaac7Dcn3eymioqpbX8qQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMEhPWmllVklLRWJlbGRT
            VHpKNk5hbjF3ZHBaWnBTRHZhZ25hWXpmeWd3ClQ5eFJvdzJoU0NLRHdTdXhPd05E
            MDZySGFHV0l0cmZHVnhZd1cvQ1hPNTgKLS0tIENmdm16OGVtc0FyOTBvSmxzNytF
            Mlk0QmpYc0FtUjk0cVlnQXhWaDBXd2sKamtJnoWNfBXbTELpOx6sOBnT/EHRVeup
            q6KTafza47NR259rGReumwKIi0BnHti+xsK9eDglXRns98eGjh7Z8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T11:48:20Z"
    mac: ENC[AES256_GCM,data:VR2CLWNf/nKAC32i3c45yy98KPBol2Eak3EO8egJb5va7xjhTP+51n1sgixtQAvVsysYp56ycj5Iu2tSalanl8y+0Bbr4xhVrU+erQKG5RqIdcVJI+1kKyF88ht1DAX7Sf5gzj5zeDDutK4HGhc+2OpHSG/sLwCBikHyBt/rCqg=,iv:xDCcrtlm8dw5oFcy939fzxW+48HdU2hqdqGRm8HyiRI=,tag:iGeA7lln38jpOzQw+IHJmA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
