---
kubernetes:
  children:
    master:
      hosts:
        master1:
          ansible_host: 10.20.30.7
        master2:
          ansible_host: 10.20.30.8
        master3:
          ansible_host: 10.20.30.9
    worker:
      hosts:
        worker1:
          ansible_host: 10.20.30.4
        worker2:
          ansible_host: 10.20.30.5
        worker3:
          ansible_host: 10.20.30.6
