---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-velero
  namespace: flux-system
spec:
  path: ./kubernetes/apps/backup-system/velero/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: velero
      namespace: backup-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
