---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-config-v1
  namespace: hemautomation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-longhorn
  namespace: hemautomation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
