apiVersion: v1
kind: Secret
metadata:
    name: vector-geoipupdate
    namespace: monitoring
stringData:
    GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:g0KqgejD,iv:1H9iZn2e8FG53quQ6DSR35LQN/A7ah/lY6/umadYE1o=,tag:zalS9gUX8MzXCewrDbEvyg==,type:str]
    GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:UExm87BD5aX5OzD8VAsJbA==,iv:cp5Wgn7Ox4x+oQcfaai3+uPekT1jOdeDnCCFSGauufo=,tag:532D3qtTl6XNs8/ijSE4yA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvU3h5QThBazZkazlya0Rm
            RUN2WWxqYVBOdXd1QjlmNmIwT1pHenlXL0ZFClV4enI4VkpzaFZrN0VYVExnOGgv
            VXZwWkl0dEdHQkRhZ1BsWVRrcENjU00KLS0tIDhITERhU1l2WFRmbkUrdlRJbDI0
            cGQ4Q0xGV1p2VkUySmFSREwyRys3eGsK8Ukcqtg2t4WFPI+Gw1beIQU4Hvtoam92
            40b7yDiECwxf2vBvR6aKGG+lMTQGCQuIljMce0T26kkj77A4rnddVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-14T20:50:52Z"
    mac: ENC[AES256_GCM,data:YMseejTYPoeqmxZstLsJ5FveXDNnsGP5PhsVSQzgXil99onYRmdB9S1AMLuV+eWx52DcWxfUfIDoXa0vNtz2rOUXEyINHY4ky1OKcUurkfI/MN8VA+XR+0AU7z1JJMmTnaOjWdoNTsp7XNVFTXehkS4PoagscAmd0Sg6CozXu2o=,iv:gm+mmzyoQfDI5EdBBISzUSWw4+/yt8JfvF/ZP2Hr6dc=,tag:ZRty/FWpQTZqldi629Kc4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
