---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: backup-system
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 3.1.2
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    timeout: 10m
    recreate: true
  values:
    annotations:
      secret.reloader.stakater.com/reload: velero-s3-secret
    image:
      repository: velero/velero
      tag: v1.10.1
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.6.1
        volumeMounts:
          - mountPath: /target
            name: plugins
    backupsEnabled: true
    snapshotsEnabled: true
    deployNodeAgent: true
    upgradeCRDs: true
    configuration:
      extraEnvVars:
        TZ: "Europe/Stockholm"
      provider: aws
      backupStorageLocation:
        name: default
        bucket: velero
        default: true
        config:
          region: eu-west-1
          s3ForcePathStyle: true
          s3Url: http://minio.storage.svc:9000
          publicUrl: https://s3.${SECRET_DOMAIN}
      volumeSnapshotLocation:
        name: aws
        config:
          region: eu-west-1
    credentials:
      existingSecret: velero-s3-secret
    schedules:
      daily-backup:
        # At 6:00am in the morning every day
        schedule: "0 6 * * *"
        template:
          ttl: "168h"
      weekly-backup:
        # At the end of the week on a Sunday morning, at 6:00am
        schedule: "0 3 * * 0"
        template:
          ttl: "338h"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        spec:
          - alert: VeleroDailyBackupPartialFailures
            annotations:
              message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partially failed backups.
            expr: |-
              velero_backup_partial_failure_total{schedule="velero-daily-backup"} / velero_backup_attempt_total{schedule="velero-daily-backup"} > 1
            for: 15m
            labels:
              severity: warning
          - alert: VeleroDailyBackupFailures
            annotations:
              message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
            expr: |-
              velero_backup_failure_total{schedule="velero-daily-backup"} / velero_backup_attempt_total{schedule="velero-daily-backup"} > 1
            for: 15m
            labels:
              severity: warning
    nodeAgent:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      tolerations:
        - key: "amd64"
          operator: "Exists"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
