---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs
spec:
  capacity:
    storage: 2000Mi
  accessModes:
    - ReadWriteMany
  storageClassName: minio-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "10.10.10.10"
    path: /nfsshare
  mountOptions:
    - nfsvers=4.2
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: minio-nfs
  resources:
    requests:
      storage: 2000Mi
