---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - ./secret.sops.yaml
  - ./configmap.yaml
  - ./server
  - ./microservices
  - ./machine-learning
  - ./web
labels:
  - pairs:
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
      app.kubernetes.io/part-of: immich
