apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: selfhosted
stringData:
    #ENC[AES256_GCM,data:lx3gGNSpMA==,iv:U3y3vK72SLKLZfqR0ZaksXwbIbO12j0oZFo+yr0Fxvc=,tag:g49ddS5zR/DLgtpo1Z6m2w==,type:comment]
    DB_HOSTNAME: ENC[AES256_GCM,data:kWS3sowGKeKqTxRjjsrtYWnzTBTbTR5dm6uIhYVQoaxlcflgwSA=,iv:Lq2fnpeNHSit8QAANiQi9g5Ly4bHlmcfZ1eVJbUkeDM=,tag:Xuce9g7xxtR7uZ2/loh5aA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:Hni/haSj,iv:nxJWoco1n9/GqSrGgZ+7x1Po4N8ZpJkRl0ZRoxOttjk=,tag:d3CRY7noagD/PtrdeqcKgA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:9sj6mGS9JPG77g==,iv:0Sj/pO3FYbZy1qkigQf0CpbVfwEYgG0uRSjvgWPIL3w=,tag:15arBxzgWCjQUH7X/uVOEw==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:odeyhBpo,iv:vC1loqzF5SKDN95n/8wLeK2CmuCgbNHp6H4oVgIybdA=,tag:BO24wVehBVaycuun26uMTg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:2YwH+YWas4C9GA==,iv:0a/969awPmD82u+Eq+KKdM1ZdnuZ4y/qM9mGcnGxJYE=,tag:S7Zv4/C1rtjElUJDEWaumg==,type:str]
    #ENC[AES256_GCM,data:3QFz0bxYUeuvGybEbAw=,iv:rJ7ye/kqK9csGnlqNtfX8onUbc9zcxLvmne3KON5G/E=,tag:i44CwLy1u+iIuZ4rV+9IgA==,type:comment]
    POSTGRES_HOST: ENC[AES256_GCM,data:nOsBFhZpHY8cg5oLLbIX3UA7z+FXKm6lLVsFxjGaWyX/W9cIQUo=,iv:uleszwBeH13S/oy0qpvQf3NRz0DWijtn8tZQ1+tEM+Y=,tag:PKOpwONZppmW5t3LQZmUNA==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:xU0szuIMx4k2ig==,iv:hpynMr/CsVLKunxCvK3KCt231rZZ6FCqewV85MQz3fU=,tag:54+QvILYGJo0onux5oulDw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:wBtqRe90,iv:grb9d4GwzBUDO3aQFyfZjH9xlbf+J4nbuVYGSXn4bY0=,tag:YsEXLhaJBOav8MKeEp+c+g==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:hHQgn4ePY40Lew==,iv:1xQJv1QxYokIwklA9yD339ODeOZqLAoK2ki3BFwRSuY=,tag:j04SSG3OaeaYAnvXLlQ5Mg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:sJ/U9SlH,iv:deBeI973OhTuGtYqxhiAocd7h3yp/9ynL3RINm4Qaww=,tag:BIII4/Eg8d9NRjV/IYT5FA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcnlZcUZiczZrKzdBSXBH
            cTAyZXZRMUdGcHR3dG0yZmNkY05ld1FsaVJBClpGZUhrWWRCVS84d0JTbE5oY0xs
            K2tnL2dreFRvVDJnSTQ0RzREUXNQY28KLS0tIHVzbTlVa2JjVHlQRHZGbWxMMW1p
            TTZFTjI5RDlNOVhDYUdKQVVLSndCWDgKe7kNa/DnZnxULznXTOCPnLDrmdh53rAQ
            9MM1Pk5JxSJ3zINuOv008YAolBtneGfzzf3aYj7/9gXycMDcS2B/0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-14T20:56:44Z"
    mac: ENC[AES256_GCM,data:Za+wdIRbWXJaLgSSf8ELnoh9aAO05LzDWSsPpL74m4jHvlXMvjJVSjrKR9i7dN342vxLXe9oaC1eYQwQX+P5DBpInwxyANfkG2c7RpTnxkzsuLTJSuTj7eG/cFpnDIZW9coAFXvoBH01EVzOv9LoJdSyp22aPxIVtT62Te+xdxg=,iv:VUuS5Ur93cZo/GIACGVaUlJkm4ZLIUq1+WhKuZzXNhY=,tag:Uygo1HuqtI1QWSN0pEeOXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
