apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: selfhosted
stringData:
    #ENC[AES256_GCM,data:Aa4sxD+E3A==,iv:LVQWztusw1XoEEXhcF8SHS68jgOoYwXSngYm86gXddM=,tag:Tp5dIhA6MYc7rUiBRxpKaQ==,type:comment]
    DB_HOSTNAME: ENC[AES256_GCM,data:lBnTSPHKFzpMm1p80Wg+ytsqxrHlXstPkGOa7dqrwfw8x0GuRsQ=,iv:3lECodD5+wAgD80SfVyShotakCMaTRkDr4J1CzYEnB8=,tag:Y8EzW09SCWFC/ulm7MBMeQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:ty6O43E=,iv:3DLFXkHiT5sZFLuujdlv/ReRdiQhX3BhPTJYXs8KJgU=,tag:IGIJlOJym2ZW4gQRJqoHZQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Gl5kGpKjvMG3nQ==,iv:bB1M5Z8Oqr6b2Bigy3ANJL/zRMlcdKvprtGBSz8F/i0=,tag:zST5QxvXM3ltTDQfVV0BmQ==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:6uYIEOuP,iv:hFaxWhLtpON0L7JhHi0PqbJTZZrqTmdJ7jvTDfGW4KI=,tag:jz5TKGxFgd49X/CsKY0Vfg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:n55dC890QM8exA==,iv:jRLYTsec1GCbPMhGnTutmzuHdLVT4pm2Y6oQWXaf4xU=,tag:vPNW8iNV0k6xY50YiNJvuA==,type:str]
    #ENC[AES256_GCM,data:m/P0So+19Ym89gVVrxA=,iv:0Ey3r2n+lK+hRrjBmQLAkEW4tRkOgzsEBenxboQTlhs=,tag:QJeVxTOkO/W65gNsEu7DrA==,type:comment]
    POSTGRES_HOST: ENC[AES256_GCM,data:lbspxL88DClEx7abmp5blVI+pvtlkW9KcR+T5UDt3EMsLGsavgc=,iv:WPiyE786KDN2pfOGpK9D4rDD/NC+FDKU82UhymhPFMg=,tag:tbFoj2tQylV0oFBqaHKLjQ==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:LfnbHkwXTG4poQ==,iv:x9S+Xhj4vscuaHsFiM2rVmtseWMOFIOtgVIsY1ISUiE=,tag:5kR+bg3XjTFNX5wJCKopsA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:X93Owss=,iv:coEjTr9Zny00DnL0vJRYXv8ymTr5gFO4Ct7fsqMK4eQ=,tag:UX3H7lPoxADyNrOoCpd91A==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:CHPDYF/5lyXFmA==,iv:YQMlmzrBgg4F2gNPor0lGv4Sjchsd2J/kqAjbc0mW0U=,tag:CzceJlPYuk0ZOHuKYwQw7w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:XeegtUVz,iv:+2So1jfaVfAqlI8NF68JcDEYPvV6UI3oDYwuNROu3Eo=,tag:LJsmJKKZfLjAHkLUsu7Q+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNFVncGM1ZXpleXFnQ2pz
            V2NYdkU1c3ROL3JnNFVJd2NrZ2N2YzJzQW40CllsSHYxOFVobVJHaTFVUmUxZFpE
            bE4xZWFqSmRHbXlFK1JlekMxVDVhTzAKLS0tIEJwdHdpTWpyb0d1Y3hqOVdTN2VK
            L3BJZnBWYmZ4UndBa2ljL3dSYXkyNVkKOF+ibzvcDWAuFFK1o+SaIA+L6x+7Rdrt
            NqX1+1ch9twNHO62wBqZN2Np75Ql6FNtk5y0OXm64u4RB/gzR11Opg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-14T22:18:22Z"
    mac: ENC[AES256_GCM,data:dfVpOGwrQWywLXxz9hdGTUH0zw7v17cn96bLh1FrTM6kFsF2cxTW8mhx+Z0ra6WoMV0KUYK+rL1Od+06Gy3op0d/nO+4z4deLU1/j4DvjmqlJzuczmZsyk6aZF8jEDJIsZnxcUa8YpuPhAugthDHmceyvl1Mj8iaRLjNG6LRHPw=,iv:5LMHbQkafV0mLaBiGM8ALb5ZDBVDxKIFVI3piOxgCp4=,tag:xbiQ4IEOWGD/fxoxc7q5dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
