apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: monitoring
stringData:
    # Immich
    DB_HOSTNAME: &dbhost postgres-v15-rw.database.svc.cluster.local
    DB_USERNAME: "{{ .immich_postgres_username }}"
    DB_PASSWORD: "{{ .immich_postgres_password }}"
    DB_DATABASE_NAME: &dbname immich
    JWT_SECRET: "{{ .immich_jwt_secret }}"

    # Postgres Init
    POSTGRES_HOST: *dbhost
    POSTGRES_SUPER_PASS: "{{ .cnpg_postgres_superuser_password }}"
    POSTGRES_USER: "{{ .immich_postgres_username }}"
    POSTGRES_PASS: "{{ .immich_postgres_password }}"
    POSTGRES_DB: *dbname
