apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:9T8ZkmNsn2vWstPvO0KSxRoEO4eztMvX2hs=,iv:jahACQemQ6ZgP8c5rSKv2lwJ4nYyUlR8RennkyRsuys=,tag:95YLozPQiybli+nwf/pr7Q==,type:str]
    api-key: ENC[AES256_GCM,data:+lp4l+SI56gxfb0KHh5Zf3U/Cj3UHcsXprV4oR7dZ7EnA/Gs0A==,iv:lrk4nAB4lL8Se3fFbDZxQvHa41sMfIlbdIdTnyyxqxY=,tag:c+7jHqjdhBzKaBdkFpl38Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQVZJNGZ6Z1lmZXFxTVlk
            ZjgyUlBEQmNKYVN4NGRibUVLbkYwTnc3R0V3CmNoUXNEVDZtOENlanBocFJmcVhF
            elJLNVJETVJSb2gxZFUwL2lEdEpuUjAKLS0tIEtESXRxNGoxa3FOMWtpTnkxMEhN
            SHQ2TUlZVW9taHk1NElUQTVMdFdzTGcKDgWamsClpmb2VnAH2+nSMPMRLtb5sKZK
            qTOIQ+jVxr3Nhto4fY8XrASiwKuoQ4dBv8J1oUkS9WxmrkAI0am4Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T11:48:20Z"
    mac: ENC[AES256_GCM,data:7tppfjfbtPIpEoVxnSt6V4JiRq90XpoAe5KNYcYFPGDaBz+67PyOlubKnd+Y83KCutb+6BxDJw5iQvKFdVYcOJ+NZw03aKqJzkJYYR3eMs1GFCYbvHPbGp0JmIGyg/03olMchFprj4pIJskh3YetORpfuhqpT7Nn7fAyfwZsimY=,iv:I5vKodAVCoDftKRQec9wITqi953Ubc0qpM8RKY0/wQ4=,tag:7wbao9pRSFwNxpA1fXDpog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
