---
# Test
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app openhab
  namespace: hemautomation
spec:
  releaseName: openhab
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dhermanns.github.io/openhab-helm-chart/
      chart: openhab
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: openhab-charts
        namespace: flux-system
      interval: 5m
  values:
    # initContainers:
      # - name: myinit-cont
       #  image: alpine
        # imagePullPolicy: IfNotPresent
        # command:
         #  - "apk add socat"
         #  - "socat pty,link=/dev/ttyACM0,raw,user=0,group=0,mode=777 tcp:ser2sock:10000 &"
         #  - sleep 200

    image:
      # -- image repository
      repository: openhab/openhab
      # -- image tag
      tag: 3.4.1-alpine
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: Europe/Stockholm
      EXTRA_JAVA_OPTS: -Dgnu.io.rxtx.SerialPorts=/dev/ttyACM0
      # -- Set the correct user id
      USER_ID: 9001
      # -- Set the correct group id
      GROUP_ID: 9001

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 8080
          languageserver:
            enabled: false
            protcol: TCP
            port: 5007

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: ipv4.stromberg.uk
          hajimari.io/icon: mdi:home-assistant
        hosts:
          - host: &host openhab.stromberg.uk
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host


    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      data:
        enabled: true
        existingClaim: openhab-longhorn
        subPath:
          - mountPath: /openhab/addons
            path: addons
          - mountPath: /openhab/conf
            path: conf
          - mountPath: /openhab/userdata
            path: userdata
    # usb:
    #    enabled: true
    #   type: hostPath
    #   mountPath: /dev/ttyACM0
    #   hostPath: /dev/ttyACM0

    nodeSelector:
      zwave: gen5

    # nodeSelector:
    #  disk: block
    # -- Configures the probes for the main Pod.
    # @default -- See values.yaml
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

#    resources:
#      requests:
#        ephemeral-storage: "1Gi"
#      limits:
#        ephemeral-storage: "1Gi"
