---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app openhab
  namespace: hemautomation
spec:
  releaseName: openhab
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dhermanns.github.io/openhab-helm-chart/
      chart: openhab
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: openhab-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      # -- image repository
      repository: openhab/openhab
      # -- image tag
      tag: 3.4.1-alpine
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: UTC

      # -- Set the correct user id
      USER_ID: 9001
      # -- Set the correct group id
      GROUP_ID: 9001

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 8080
          languageserver:
            enabled: false
            protcol: TCP
            port: 5007

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: ipv4.stromberg.uk
          hajimari.io/icon: mdi:home-assistant
        hosts:
          - host: &host openhab.stromberg.uk
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host


    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      conf:
        enabled: true
        mountPath: /openhab/conf
        accessModes:
          - ReadWriteOnce

      userdata:
        enabled: false
        mountPath: /openhab/userdata
        accessModes:
          - ReadWriteOnce

      addons:
        enabled: false
        mountPath: /openhab/addons
        accessModes:
          - ReadWriteOnce

      java:
        enabled: false
        mountPath: /openhab/.java
        accessModes:
          - ReadWriteOnce

      storageClass: "longhorn"

      accessModes:
        - ReadWriteOnce
      size: 1Gi

    influxdb:
      enabled: false
      architecture: standalone
      database: openhab
      authEnabled: false
      persistence:
        enabled: false
        storageClass: "longhorn"
        accessModes:
          - ReadWriteOnce
        size: 8Gi

    grafana:
      enabled: true
      persistence:
        enabled: false
        storageClass: "longhorn"
        accessModes:
          - ReadWriteOnce
        size: 4Gi

    # -- Configures the probes for the main Pod.
    # @default -- See values.yaml
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
