---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app openhab
  namespace: hemautomation
spec:
  releaseName: openhab
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dhermanns.github.io/openhab-helm-chart/
      chart: openhab
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: openhab-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      # -- image repository
      repository: openhab/openhab
      # -- image tag
      tag: 3.4.1-alpine
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: UTC

      # -- Set the correct user id
      USER_ID: 9001
      # -- Set the correct group id
      GROUP_ID: 9001

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 8080
          languageserver:
            enabled: false
            protcol: TCP
            port: 5007

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        hosts:
          - host: openhab.stromberg.lan


    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      conf:
        enabled: false
        mountPath: /openhab/conf

      userdata:
        enabled: false
        mountPath: /openhab/userdata

      addons:
        enabled: false
        mountPath: /openhab/addons

      java:
        enabled: false
        mountPath: /openhab/.java


    # -- Configures the probes for the main Pod.
    # @default -- See values.yaml
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
