---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-longhorn
  namespace: hemautomation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
