---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ser2sock
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: ser2sock
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: tenstartups/ser2sock
      tag: amd64
      imagePullPolicy: Always
    env:
      TZ: "Europe/Stockholm"
      LISTENER_PORT: 10000
      BAUD_RATE: 115200
      SERIAL_DEVICE: "/dev/ttyACM0"
    securityContext:
      privileged: true
    tolerations:
      - key: "arm"
        operator: "Exists"

    persistence:
      usb:
        enabled: true
        type: hostPath
        mountPath: /dev/ttyACM0
        hostPath: /dev/ttyACM0
        # hostPathType: CharDevice

    nodeSelector:
      zwave: gen5

    resources:
      requests:
        memory: 50Mi
        cpu: 15m
      limits:
        memory: 250Mi
