apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openhab-tls
  namespace: default
spec:
  dnsNames:
    - yourdomain.org
  secretName: openhab-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
