---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data
  namespace: hemautomation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
