apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:IxKX5HIc7PFQLb09,iv:CzTMz7ApfndP6Qtn0eYxIAXsloZAfTEHXQoThvA6P30=,tag:68fgQ3E05/Xi2HmWTcKtmw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:JmXo4VzLPgRWqNPi+U+gSDcyeXEVUXhSx4M=,iv:2gk0MqJ8L/btqc+aXcLN+U+LAQAwrTztvWbpNB3xxAA=,tag:rcR5TVZGqNOZaxQXyAPUVQ==,type:str]
    SUPER_SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:F54/f9dS/esXMA==,iv:pzs8BezLxBbXYL+3Bx9slbyPdiqi1PZYL8FWjkleq7o=,tag:9aGzYiScsTDvJXlwrnCLDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUnpscXFySEYyUDhLMHM0
            YkxxdVlmNVQrSWdjdjRxMWtNOXM5cjdWVEhFClBrVEppN1BRQUxrcnpBUDJnbnAz
            NEZQd3Y4YVkzby9zbHNnTmxJcDY4ZUkKLS0tIGQ4emkvRi8vbC9lWE54TWJvMnNv
            aG0wbmlmZGY4VzVZWTd5bDJ1N2xqaDgKZVo0qoDlkuMKNwgZ8i358IMFa23SYNgn
            3GCdcvbZc2TU0SROoi9tX0KeQvOM9uG4u7AuixFQnGU4nATDLcmgsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T13:57:46Z"
    mac: ENC[AES256_GCM,data:s9VnfyLMVVXex4gY3GYIMWpk5munBftdv7a1u3A7AwGo1bRE2Nz0pEywtS4Tfss8KB33a0M1F/D64JSzuLhiiuv5jMgUwxKeKJJWrDkOFmA0WjCVhgVqaM1dTC6mKbgH72HvqvhkwosYkrOrlEstniD03bpE01zl6zfILJsbA/E=,iv:KtL9dn47IE2BAsf3OyCm5yuZFVl8RRsNh3fN9s0sAmI=,tag:UkCm+AiVtu7FbfGtSx2YpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
