apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kOfkawjW5F395Z5w,iv:s3ALQao597TPIGe6xWVXLj0isA0YoW1XiM2pX2L9w+I=,tag:51RRPr1yp+fyOVUCJyM2Ow==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:lTs/wEryXhMzvxOYwOvcIciAMc1nbizGc2M=,iv:JvXiYuUZuL1vhpKZIWvsiK0d+lBZp97wMg2TczYjoxs=,tag:XqRK9Ijx0kC+VrDE7NMUQA==,type:str]
    SUPER_SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:k53V5AEeoq/s2Q==,iv:HWERDHMZiahTBBP4xjF2Y38QizVVyNH2JvrB1wBFsYE=,tag:2gRYsKzUXr5SghwoJwcS5w==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:yVmwzmWjJ5IvSZs=,iv:NJyWXLO31SSER8BDFM2++a6nPIgJiPOITNN8CBaLVkI=,tag:mBN6aA5EAC5PukthxYiH4Q==,type:str]
    MINIO_USER: ENC[AES256_GCM,data:E4T2PPQ=,iv:qZ1UvmLx6lDBp1GtvLaqUCr+qTmSEKQFtFJcnTD1XVE=,tag:RFvORLqVm2W3RDAkVvsfNw==,type:str]
    MINIO_PASSWORD: ENC[AES256_GCM,data:dBBooK62Tr+vRg==,iv:bLRZ5gG/jLNfyb2l8TCTSkwFmXwjPDOCTiMMEXYUHZI=,tag:E9k8rOdYsYQUAebCak7k6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTXFIcXk2OVAxM1dxU3ls
            UGdYS0htaFhnQXh5SVV3bHRuWkV1c1UrMTJ3ClNlRkRVY2VEeStPSENVM1ZqOVFk
            Q1JMMFBEZ3hBakJnWmVPOTkwYnBxdFkKLS0tIEZuUVNHQnhCTG40amFXUUxnVTQ2
            RnVBUGsyc1Z2Y1cwZjBncjZHM1lwNWsKf6V7bCpGqKF0oYlopykjnuRdnQ6V1tEr
            fS2waUaHfzSIpS46/PezdVw0/q+VvFbp9vcygLstKM+pPMNcH5bBmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-28T21:45:39Z"
    mac: ENC[AES256_GCM,data:ZEdWbP9DSoOicsdw3jz7uQre1N0vK3SNsjFcQ887VHS3vz1kuy9F/Hx94pfc5PjSAPjb6/1v6BLAiilOIkVEcBueGhjqVL3JtG+YWxYWIMX04sEpQMxewvitbsXYDur3TEsE1wZrNQiU1WG75ujEgQRzxw5Bp6zATUB9oZjpMGo=,iv:7RTHJuuqqHp7lk+X6+iABsyLqyjUxwygKij4OG/Bvgo=,tag:FmtWxeJf+OlhzSgAqRNEHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
