---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Stockholm"
  KUBE_VIP_ADDR: "10.10.10.254"
  METALLB_LB_RANGE: "10.10.10.100-10.10.10.150"
  METALLB_K8S_GATEWAY_ADDR: "10.10.10.100"
  METALLB_INGRESS_ADDR: "10.10.10.101"
