---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Stockholm"
  KUBE_VIP_ADDR: "10.20.30.254"
  METALLB_LB_RANGE: "10.20.30.100-10.20.30.150"
  METALLB_K8S_GATEWAY_ADDR: "10.20.30.100"
  METALLB_INGRESS_ADDR: "10.20.30.101"
