---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 30m
  chart:
    spec:
      chart: promtail
      version: 6.9.3
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    extraArgs:
      - -client.external-labels=hostname=$(HOSTNAME),cluster=${SETTING_CLUSTERNAME}
      - -config.expand-env

    config:
      clients:
        - url: http://loki-gateway/loki/api/v1/push
    serviceMonitor:
      enabled: true
    tolerations:
      - effect: NoSchedule
        operator: Exists
