---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/helmrelease_v2beta1.json
# Test
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app pgadmin
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: dpage/pgadmin4
      tag: "6.21"
    controller:
      type: statefulset
    envFrom:
      - secretRef:
          name: pgadmin-secrets
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/icon: simple-icons:adminer
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    podSecurityContext:
      runAsUser: 5050
      runAsGroup: 5050
      fsGroup: 5050
      fsGroupChangePolicy: "OnRootMismatch"
    persistentVolume:
      enabled: true
      existingClaim: pgadmin-config-v1
    podAnnotations:
      reloader.stakater.com/auto: "true"
    resources:
      requests:
        cpu: 15m
        memory: 164M
      limits:
        memory: 236M
    serverDefinitions:
      enabled: true
      servers:
        postgres:
          Name: postgres
          Group: Servers
          Port: 5432
          Username: postgres
          Host: postgres-any.default.svc.cluster.local
          SSLMode: prefer
          MaintenanceDB: app
