---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: pgadmin-oauth-configmap
    files:
      - ./config_local.py
generatorOptions:
  disableNameSuffixHash: true
