---
# Test
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
  annotations:
    kyverno.io/ignore: "true"
spec:
  nodeName: worker1
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14.7
  primaryUpdateStrategy: unsupervised
  affinity:
    nodeSelector:
      disk: block
  storage:
    size: 20Gi
    storageClass: longhorn
  superuserSecret:
    name: postgres-superuser
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
