---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./cluster.yaml
  # - ./scheduledbackup.yaml
  - ./prometheusrule.yaml
  - ./service.yaml
labels:
  - pairs:
      app.kubernetes.io/name: postgres-cluster
      app.kubernetes.io/instance: postgres-cluster
      app.kubernetes.io/part-of: postgres-pg
