---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dashboard
  - ./secrets.sops.yaml
  - ./helmrelease.yaml
  - ./datasource.yaml
  - ./rules.yaml
  - ./servicemonitor.yaml
