apiVersion: v1
kind: Secret
metadata:
    name: loki-secrets
    namespace: monitoring
stringData:
    S3_BUCKET_NAME: ENC[AES256_GCM,data:ptTuNA==,iv:2rMI0sbYlufXZiInhnBh+3anoMbZimILsItmE1yF1Kw=,tag:bqzcozZbBhZ7JX+LBmpLfg==,type:str]
    S3_BUCKUP_HOST: ENC[AES256_GCM,data:L751ZGaFLOhW8w==,iv:L7X63OL2qEbcCXR8uMOs7gK1KGYR+0J1z7BfRpFgKX0=,tag:eH5Fn+3TCJO60N+fbsrHNg==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:bjmgo/k=,iv:mpsOAwxuaW4tgEuMdlu9XSJYSapUUkownlGLweVTmW8=,tag:eiexDchybFdQRmp4j0vvuw==,type:str]
    S3_SECRET_kEY: ENC[AES256_GCM,data:1779ebE3pph2Jw==,iv:1exgGuaSohxzxgIIw9w9t7OCYSctqg9jFdlpt2N3ZEI=,tag:VWjV8YhUZXwjHF0oHaz0bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRGJpY090bFFyVmhSU3NN
            VG13SmVaYjdxSlF1UVozT0ROeEpMS3h2dlhBCk5ZRnB3MU5wM3VLenNvTTBjdDRY
            RkVBaDk0c0JibXlGaGY4V1ZSOEsxeGMKLS0tIHNNcDlDUUxka05qMHBJVk5HTkg4
            aC84Q0hHU3B2cUJJV29WamNjbURTZGsKo3eaaeEqKPXKyQxNisxs9+95fsgR81kU
            KdhIQxB+UXgxiYawds905ZcV4YdLrRagyZTHWlBbCX2UVWYWn5kVSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-14T18:09:28Z"
    mac: ENC[AES256_GCM,data:Udr68AYvxjjKBk+eWslvb7hc5KTThlfOFvDujzGlQIF2LUf/qVysxCgWZbwY/ci+5AyuUHf4YbUPgpSwdBFslvc28MUJhqETwZcJ2kuNFhojOFUIkEs3PVvp0/7tkc2TNsB0cJffLSGfPgj+ndna5Nfnx5WW5HtRKku4MBDQ23I=,iv:7Lf4f4nbSCzXQY0XT4quHI7NvKa9HB2qy31+R5aL9yw=,tag:+SE4+ntkQ+9OPj9kRds/XA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
