apiVersion: v1
kind: Secret
metadata:
    name: loki-secrets
    namespace: monitoring
stringData:
    S3_BUCKET_NAME: ENC[AES256_GCM,data:c0iavQ==,iv:dBNUmCApN8E2Wie8s2xwLYQjI7Yl6SJuJeFM+rLOwDc=,tag:SqpvAsT25cpOKlc1GSWO/w==,type:str]
    S3_BACKUP_HOST: ENC[AES256_GCM,data:kvUuYsam2Nv6+A==,iv:XlkP7/ew4ngm7z9Nx+uF3WH76T+vICF7H+ZG0LJgN3o=,tag:yvo20DZ/R1BaI26nbeHGGA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:tycq1+I=,iv:2jefpcmVXCXUanU+Tvmia1+wR+NKkhHnEMiYohLFPa8=,tag:9mNbPndpLDJpyN0/trKFFA==,type:str]
    S3_SECRET_kEY: ENC[AES256_GCM,data:2qa0OOkQzbc1kA==,iv:iwdGti1ZZPJHov0jASCsnzOPHHaCR7PLS16dBvxLYoI=,tag:14QPTQFTG+Mkq52YmAyX0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc3Q0bUlTSjB5RkdKelJR
            REdaSG4wQ2JZUG5oTWppcGF3bnZVeWdyVGhBCk1hTVdsUDkvelpRSThIYXVIYWZY
            dnpKb0JURTBrL0RsaHBRSU1HbDR3ZEEKLS0tIDFYZDQxNStxc2dSTlE1eHY0Zkx6
            aGRWZWZYOE85Z3Z2YmZVL1VrM3JSYTQKZuzQPtne3bNBTq5WAE4HY05PS/fK5g2U
            jysYPTTKCw+69aLdxnxTg5UIH8HbsZaam3CspIrfoTk05N97qgzWHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-14T17:37:51Z"
    mac: ENC[AES256_GCM,data:9wedIIjRzL9kmhSU+2xL7JDMto1s3uGisQXxhw6YKGT2nOVIMM2hvgbTDWX2r+TsLhhryLOKiUJ0P3j2UviavsCyDJwdwnm3sFCSiYpJYMkMa3CmvNWKBzdwZf+JsJ3zVg6phxU2ftLoRLOt7Czl8LGq29aYuImkT222DTo1h+w=,iv:2TaxUtuP0mK4xG7iXGdTVKJOvl308phhofY/BUjVwYw=,tag:JQhfcKv+ea/XkAQErf2u2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
