apiVersion: v1
kind: Secret
metadata:
    name: loki-s3
    namespace: monitoring
stringData:
    minio_access_key: ENC[AES256_GCM,data:XHM90vc=,iv:8TUOIb5iWELvTuydODUVDEqb8RHPO68pcAQpfl55DfM=,tag:sl+vlOf9ibCkA7nCwXpbNg==,type:str]
    minio_secret_key: ENC[AES256_GCM,data:KdnP4XFUGXkRFQ==,iv:Sj0uLmTwUHHDk/LRn2S3TdhTT7poEbOa+j38DahRFfY=,tag:Tee88SE2bUHkGU/LqLNl1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZU14OVZpYW16L1pVdEUz
            dXBLNGNjTnNUSEx0bTlWSjkvdjRhVmFlQ0VVClpYZWsrYUZqYkVOaEYzRHEwVjd6
            cWo3Y1lCQmxYTVBJdjIzOVpTK3NISkkKLS0tIGNRejJIY08xM1E4SzJ5SDVpT0pH
            RENsQnpkOGh5SjV2K3dXam9QdlVMaWcK/H9YJE4zqUkS+2hKxUmEe72wr+VN7mBw
            ZI1GOdk7Mgd1ifuUJItqDVuryljRq3BoY1joPPF9Q0timAHP+08P9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T21:40:46Z"
    mac: ENC[AES256_GCM,data:sW4+GYZY04L36h/cnzzDPhYRA6Uq6tFzku1SlMJ99eU/7J2U/hootc3iRGosTH4q9VroILRQUCCvNYJnIBnHoX9mVv6QV8FEEv/H5Xsjsp4C6BXmyhz2ee/lRtIM07N/mndhW4pvvlFHKke9s/gD3OKuFHPDbdpCKCxet7WklM8=,iv:snlc4NVSePpo0VbU2uAHEuEyrHoVZh8uXXfkeRkbmog=,tag:vfdS+goBTt8euistqo3MeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
