---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: 12.2.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      postgresql:
        auth:
          postgresPassword: "${POSTGRES_ADMIN_PASSWORD}"
          username: krister
          password: "${POSTGRES_PASSWORD}"
          database: openhab
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: "15.1.0"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hajimari.io/enable: "false"
        hosts:
          - host: &host "postgresql.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    auth:
      enablePostgresUser: true
      postgresPassword: "${POSTGRES_ADMIN_PASSWORD}"
      username: krister
      password: "${POSTGRES_PASSWORD}"
      database: openhab
    primary:
      persistence:
        enabled: true
        existingClaim: postgresql-data
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    nodeSelector:
      disk: block
