# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-secret
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:DXGCuwwmvw==,iv:yApKLj2ch4BqsqRsVI5QVuKRa7H7obaur4HbSQeq80E=,tag:c0CueizKKWP29A1Jh+Im7w==,type:str]
    password: ENC[AES256_GCM,data:hA1XmkQ1pt9QNg==,iv:pac35kC61S62bHlWHpIJz1yb+7jnyHIP3cbuBYvb9S0=,tag:7iwF0Y+lZKl1VxHDXkXeIw==,type:str]
    adminpassword: ENC[AES256_GCM,data:OEnS1lrR4XzK6A==,iv:57dDe908rHAyUfxXUpABk958U0rlTA74XhmMKTb4T9I=,tag:bEwHIl6XS7v/9BHCYTRPrg==,type:str]
    userpassword: ENC[AES256_GCM,data:iazIGJfLSCWzYQ==,iv:TAVViSE7ncm21o167ScOI7WxJdGP/kodL+FWl51gjnk=,tag:INEeMa6apMAawFAo7jMRSg==,type:str]
    replicationpassword: ENC[AES256_GCM,data:YctbMNtuJRYbQg==,iv:oFffp/GJPLHyZbfZ5tcOuhyz1XT3ZoV4enl6aKRZ200=,tag:GP95Sp6IkCAtTg9opLFOcg==,type:str]
    postgres-password: ENC[AES256_GCM,data:xGXNoEPzgLzFrA==,iv:RLrA8dGKtb3tCJpcnSHDWdBgJ/E/1ROuCaXIL2OV9Fk=,tag:FR66itk1zlUqQDMRLWIkdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaY2x1cE5JN1RNcHhvMjdm
            ZXhINnpTOFNoaXJOTXNtTnhzd0pkaTZEd2xnCmlrSEd6eFZRbjVRaVJLRk1iLzFI
            Q2dSQjMrQjFock92Q21Ed215TkdyTjQKLS0tIDRFWGV5cE9SQ3FrUmxDbm1BQmVw
            SXBURTlQZlVtb0VRbHRkaWl4ZytxODQK3Yo/cu7jcUmqmtu7gutyh1xzdlRSmuz7
            5fc5R+kppTo/D41C3GG4nE/82n2tP761MhapqzuufYtdp/+rtc0peg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-12T16:25:58Z"
    mac: ENC[AES256_GCM,data:hQs1RMggo/8ENtzHBgIRANba9PVQWci4SF37LhnbNdQXN3wurtVaoDKsYeSw4a6xe/NbRyCxAgBePWhcOT/MAAz/ovBdCOCfCEei2lbVKecU8HlGG9kuTRZyCBgtJOrTw0cSMWT75gxE0LeDHwvCjCBJOo27WrmB/aWnBCziphY=,iv:LpdFCGDMH3rIrQ1RT7Bd9pdWLyCGKu46ulvkX7i4iUk=,tag:tzjZ9n3TDo3a1oCUUixO4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
