# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-secret
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:vqCDogKMUQ==,iv:kZMIvutZ9ns4sNQ3iSfxva/4iELAP4gFi3tavpyH0Ag=,tag:UDJQVBzP0ZbM6/bu2JSFUA==,type:str]
    adminpassword: ENC[AES256_GCM,data:8hxy2zoYjis0BQ==,iv:3iw8IC/PvNjggcs+2Cw/E1O/3RCTNKnA90BsvX3v8x0=,tag:E4EOTfu25e862tCrxDKI3A==,type:str]
    userpassword: ENC[AES256_GCM,data:QFT/2YKhNOAtSQ==,iv:HWp1mZVM4PwolPu+UNJwNN8VcEhq9HTh0DC2P2YDfqg=,tag:YtH2DDXYHaAH/W7CPE/rwg==,type:str]
    replicationpassword: ENC[AES256_GCM,data:unG3b0wdtZEOOw==,iv:EmFEJsUgkW0TyvuO5RajwoELYGyu4EA1NrSYyjh345Q=,tag:29jZ2IYfKSwiDFC3dOpH0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8u0lcf95wxxgk6p5vzuv94z9jk0pmeznzmnl47pcf8a7yyffp4s9g3mew
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRCt1OE04Tm9uYVF4UGRZ
            Z1FNVnRUWCs1bUZxUlRqRU9teUdQSHdYMzBJCjd0aWIvQUloUTNIbTVoeTIzRyts
            OVRwaTc5NDRjVStVV0lUVEFZditTV0EKLS0tIEhHY291WERXYkwvRjZTTXFreUts
            d3dRSGZjSkxtSUd6a1NMUyt3SGlUa2sKge4g2DYQghVkTXEmdCNsokHhI+4hWFku
            TlOHO3av3I5z3NM1t2COhgAOxzS+rUnR8QEhZWIe6hwZuOUYZhqYgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-12T16:15:47Z"
    mac: ENC[AES256_GCM,data:is49DRURPq7JVh2W4dzXF67ZWZpPItqTQpWJedIW/uJabOuwieJXUOnOm5IWGUmMVcrXl6r2KHUlPZpUPfzuh9dgaAG3f5X71P75z1wviywo3kBtUdH7a/Z3HsltCpgyOo2n5ex0argIch1+/b1O8npMIFQKtkX0YaocZ2L3SeA=,iv:Wk8akINXGsQoFNVu+naGTU2Dscw+2CrjqOfRm9Tu3Hs=,tag:B7oNq+X0rrBpWzhIXlN8kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
