---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-microservices
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
    - name: immich-server

  values:
    controller:
      replicas: 2
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.50.1

    command: /bin/sh
    args:
      - ./start-microservices.sh

    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-configmap

    service:
      main:
        enabled: false

    persistence:
      library:
        enabled: true
        type: nfs
        server: "10.10.10.50"
        path: /mnt/data/Media
        mountPath: /usr/src/app/upload

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      # limits:
      #   memory: 500Mi
